# Generated by Django 5.0.1 on 2024-02-01 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StorageStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupiedStoragePercent', models.DecimalField(decimal_places=2, max_digits=3)),
                ('wasteType', models.CharField(choices=[('PA', 'Paper'), ('GL', 'Glass'), ('PL', 'Plastic'), ('ME', 'Metal'), ('OR', 'Organic'), ('WO', 'Wood'), ('NR', 'Non-Recyclable')], max_length=2)),
                ('storageCapacityCubicMeters', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
