# Generated by Django 5.0.1 on 2024-02-03 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storagestation',
            old_name='storageCapacityCubicMeters',
            new_name='occupied_storage_percent',
        ),
        migrations.RenameField(
            model_name='storagestation',
            old_name='wasteType',
            new_name='waste_type',
        ),
        migrations.RemoveField(
            model_name='storagestation',
            name='occupiedStoragePercent',
        ),
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_detail', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('storage_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.storagestation')),
            ],
        ),
    ]
