# Generated by Django 5.0.1 on 2024-02-04 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_storagecapacitycubicmeters_storagestation_occupied_storage_percent_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operationlog',
            old_name='date',
            new_name='operation_date',
        ),
    ]
