# Generated by Django 5.0.1 on 2024-02-04 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_date_operationlog_operation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagestation',
            name='was_pickup_requested',
            field=models.BooleanField(default=False),
        ),
    ]
