# Generated by Django 5.0.1 on 2024-02-05 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_storagestation_was_pickup_requested'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storagestation',
            name='occupied_storage_percent',
            field=models.IntegerField(default=0),
        ),
    ]
